name: Build template

on:
  push:
    branches:
      - master
  pull_request:
  registry_package:

jobs:
  build-template:
    name: Build template
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest-full

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build pdf
        run: |
          echo -e "\033[1;35mCompiling banking style...\033[0m"
          latexmk -pdflua ./template.tex
          mv template.pdf template_banking.pdf

      - name: Upload pdf
        uses: actions/upload-artifact@v4
        with:
          name: template.pdf
          path: ./template_banking.pdf

      - name: Upload log
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: template.log
          path: ./template.log
